# roles/database/tasks/main.yml
---

- name: Add apt key 
  command: apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'

- name: Add MariaDB Repo 
  apt_repository: 
    filename: MariaDB-10.2 
    repo: deb [arch=amd64,arm64,ppc64el] https://ftp.igh.cnrs.fr/pub/mariadb/repo/10.5/ubuntu bionic main
    state: present

- name: 1c. Install MariaDB server package
  apt: name=mariadb-server state=present

- name: 2. Start Mysql Service
  service: name=mysql state=started enabled=true

- name: Install python Mysql package #required for mysql_db tasks
  apt: name=python-mysqldb state=present

- name: Determine required MySQL Python libraries.
  set_fact:
    deb_mysql_python_package: "{% if 'python3' in ansible_python_interpreter|default('') %}python3-mysqldb{% else %}python-mysqldb{% endif %}"

- name: Ensure MySQL Python libraries are installed.
  apt: "name={{ deb_mysql_python_package }} state=present"

- name: 3. Create a new database
  mysql_db: name=demo state=present collation=utf8_general_ci

- name: 4. Create a database user with privilege on demo database 
  mysql_user: name=demo password=demo priv=demo.*:ALL host=localhost state=present

- name: 5a. Copy sample data
  copy: src=dump.sql dest=/tmp/dump.sql
  
#- name: 5b. Insert sample data
#  shell: cat /tmp/dump.sql | mysql -u demo -pdemo demo

- name: 6. Install MySQL extension for PHP
  apt: name=php-mysql state=present

# - name: Create db new users
#   mysql_user: name=user1 password=cloudaccess priv=demo.*:ALL host=localhost state=present

# - name: Create db new users
#   mysql_user: name=user2 password=cloudaccess priv=demo.*:ALL host=localhost state=present

# - name: Create db new users
#   mysql_user: name=user3 password=cloudaccess priv=demo.*:ALL host=localhost state=present

- name: Create db new users
  mysql_user: name="{{item}}" password=cloudaccess priv=demo.*:ALL host=localhost state=present
  with_items:
     - user1
     - user2
     - user3
     - user4
     - user5
     - user6 
     - user7
     - user8
     - user9
     - user10
     - user11
     - user12
     - user13
     - user14
     - user15
     - user17
     - user18
     - user19
     - user20

